[package]
name = "lisp_rs"
version = "0.1.0"
authors = ["logger <157056982@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
